version: "3.7"
services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'wurstmeister/kafka:latest'
    container_name: kakfa
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"
  tweet:
    image: tweet
    container_name: tweet
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - mongo_db